### PR TITLE
Added medals

### PR DESCRIPTION
**Pull request by Priyanshu1035**
Screenshot 2024-08-06 090229
Added medals as per the issue #7

### CODE REVIEW

**Comment by sailingsam** [comment]
Hi priyanshu, we need two changes here, 

- We are already using react-icons so no need install another dependency or better thing to do is 
  - Download these icons 
  - https://icons8.com/icon/33486/gold-medal
  - https://icons8.com/icon/23876/silver-medal
  - https://icons8.com/icon/23875/bronze-medal

- No need to make another column, just where house name ends add these to right of them

**Comment by Priyanshu1035** [comment]
Is it fine now?

**Comment by sailingsam** [comment]
Great! Thanks man, you are the first official contributor for this. If you are from batch of 28, would love to connect, treat on me (small one D) ;)

**Comment by Priyanshu1035** [comment]
I am from batch of 26.

**Pull request merged**
